#pragma config(Sensor, S1,     GYRO1,          sensorAnalogInactive)
#pragma config(Sensor, S2,     Sonar,          sensorSONAR)
#pragma config(Sensor, S3,     Touch,          sensorTouch)
#pragma config(Sensor, S4,     GYRO2,          sensorAnalogInactive)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          MotorB,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          MotorC,        tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "ConstAndVaribales.h"
#include "Functions.h"
#include "drivers/hitechnic-gyro.h"
#include "turn.h"
#include "run.h"
#include "balancing.h"




task main()
	
{
	nMotorPIDSpeedCtrl[motorB] = mtrSpeedReg; //Motorspeedregulator, prevents sudden motorpower changes
	nMotorPIDSpeedCtrl[motorC] = mtrSpeedReg;

	batteryPower=Check_Power() // Checks batteryVoltage, see Functions.h
	RaceMode=Check_if_Racemode(); // Checks if RaceMode is enable, see Functions.h

	PlayImmediateTone(2000, 20); // Play tone, get ready for calibration
	nPidUpdateInterval = 10; // A builtin function which sets or update interval
	wait10Msec(200);

	Calibrate_gyros(); // Calibrate the Gyros, see Functions.h

	nMotorEncoder[motorB] = 0; // Sets the position of the encoders to 0, the start position.
	nMotorEncoder[motorC] = 0;


	while(true)
	{
	WheelPositionIntegral = 0; // reset the WheelPositionIntegral, to avoid undeclared valus
	Start_position = nMotorEncoder[MotorB]; // sets our variable to the start position (0)

	balancing(); // execute balancing
		
	if(counter%2 == 0) // if counter is even --> run-mode
		run();
	}

}
